micronaut:
  server:
    port: 8081
  application:
    name: service1
netty:
  default:
    allocator:
      max-order: 3

grpc:
  server:
    enabled: true
    port: 8091
    keep-alive-time: 3h
    max-inbound-message-size: 1024

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/demo`}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:postgres}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

flyway:
  enabled: false
  datasources:
    default:
      enabled: false